import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {JSDOM,VirtualConsole} from 'jsdom';import {pages} from './public-pages.mjs';import {policy} from './public-data.mjs';
const base=fileURLToPath(new URL('./dist/',import.meta.url));
import {origin,basePath} from './site-config.mjs';
const fileFor=p=>path.join(base,p.endsWith('.html')?p:p+'/index.html');
const docs=new Map(Object.keys(pages).map(route=>[route,new JSDOM(fs.readFileSync(fileFor(route),'utf8')).window.document]));let links=0;
for(const [route,d] of docs){assert.equal(d.querySelectorAll('h1').length,1,route+' h1');assert(d.querySelector('main#main-content'));assert(d.querySelector('meta[name=description]').content.length>40);assert.equal(d.querySelector('link[rel=canonical]').href,origin+route);assert(d.querySelector('meta[property="og:title"]'));assert(d.querySelector('meta[name="twitter:card"]'));const ids=[...d.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size,'Duplicate ID '+route);
 for(const el of d.querySelectorAll('[href],[src],[poster]')){const ref=el.getAttribute('href')||el.getAttribute('src')||el.getAttribute('poster');if(!ref||/^(https?:|mailto:|data:)/.test(ref))continue;const url=new URL(ref,origin+route);assert(url.pathname.startsWith(basePath+'/'),`${route}: unprefixed path ${ref}`);const localPath=url.pathname.slice(basePath.length)||'/',target=docs.get(localPath);if(target){if(url.hash)assert(target.getElementById(url.hash.slice(1)),`${route}: broken anchor ${ref}`);}else assert(fs.existsSync(path.join(base,localPath)),`${route}: missing asset ${ref}`);links++;}
}
assert(docs.get('/login/').querySelector('meta[name=robots]').content.includes('noindex'));assert(!docs.get('/login/').querySelector('input[type=password]'));assert(!fs.readFileSync(path.join(base,'sitemap.xml'),'utf8').includes('/login/'));
// Public policy explanations must match the actual engine, not an aspirational workflow.
const contract=JSON.parse(fs.readFileSync(new URL('./tests/policy-contract.json',import.meta.url),'utf8'));for(const [action,,outcome] of policy.slice(0,-1)){assert.equal(outcome,contract.actions[action],'Policy mismatch '+action);}
function boot(route,options={}){const dom=new JSDOM(fs.readFileSync(fileFor(route),'utf8'),{url:origin+route,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole().on('jsdomError',error=>{throw error;})}),w=dom.window;w.matchMedia=query=>({matches:query.includes("pointer: fine")?!!options.fine:!!options.reduced,addEventListener(){}});if(options.depth)w.HTMLElement.prototype.getBoundingClientRect=function(){return {top:100,left:20,width:400,height:300};};if(options.observe){w.HTMLElement.prototype.getBoundingClientRect=function(){return {top:1000};};w.IntersectionObserver=class{constructor(callback){w.revealCallback=callback;}observe(){}unobserve(){}disconnect(){w.revealDisconnected=true;}};}w.ResizeObserver=class{observe(){}};w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLMediaElement.prototype.pause=function(){this.dataset.wasPaused="true";};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};for(const s of ['preferences.js','public.js','depth.js'])w.eval(fs.readFileSync(path.join(base,s),'utf8'));return dom;}
for(const route of Object.keys(pages)){const dom=boot(route);dom.window.close();}
// Reveals must remain readable when motion is disabled or unavailable.
const animated=boot('/',{observe:true}),aw=animated.window,ad=aw.document;assert(ad.querySelectorAll('.reveal-ready').length>0);const reveal=ad.querySelector('.foundation-card');aw.revealCallback([{target:reveal,isIntersecting:true}]);assert(reveal.classList.contains('is-visible'));ad.querySelector('.motion-toggle').click();assert([...ad.querySelectorAll('.reveal-ready')].every(e=>e.classList.contains('is-visible')));assert(aw.revealDisconnected);animated.window.close();const reduced=boot('/',{observe:true,reduced:true});assert.equal(reduced.window.document.querySelectorAll('.reveal-ready').length,0);reduced.window.close();assert.equal(docs.get('/').querySelectorAll('#agents .role-preview>a').length,6);
// Mouse perspective is bounded, clears on pause/leave, and ignores touch/reduced motion.
const tilt=boot('/',{fine:true,depth:true}),tw=tilt.window,td=tw.document,card=td.querySelector('.foundation-card');
const pointer=(target,type,kind='mouse')=>{const event=new tw.Event(type);Object.assign(event,{pointerType:kind,clientX:1000,clientY:-500});target.dispatchEvent(event);};
pointer(card,'pointerenter');pointer(card,'pointermove');await new Promise(resolve=>tw.requestAnimationFrame(resolve));assert.equal(card.style.getPropertyValue('--depth-y'),'1.50deg');assert.equal(card.style.getPropertyValue('--depth-x'),'1.50deg');assert(card.classList.contains('depth-active'));td.querySelector('.motion-toggle').click();assert.equal(card.style.getPropertyValue('--depth-y'),'');assert(!card.classList.contains('depth-active'));td.querySelector('.motion-toggle').click();pointer(card,'pointermove','touch');await new Promise(resolve=>tw.requestAnimationFrame(resolve));assert.equal(card.style.getPropertyValue('--depth-y'),'');pointer(card,'pointermove');await new Promise(resolve=>tw.requestAnimationFrame(resolve));pointer(card,'pointerleave');assert.equal(card.style.getPropertyValue('--depth-y'),'');tilt.window.close();
const still=boot('/',{fine:true,depth:true,reduced:true}),sw=still.window,sc=sw.document.querySelector('.foundation-card');const event=new sw.Event('pointermove');Object.assign(event,{pointerType:'mouse',clientX:300,clientY:200});sc.dispatchEvent(event);await new Promise(resolve=>sw.requestAnimationFrame(resolve));assert.equal(sc.style.getPropertyValue('--depth-y'),'');still.window.close();
const home=boot('/'),w=home.window,d=w.document;const click=s=>{assert(d.querySelector(s),s);d.querySelector(s).click();};
click('[data-department="Product"]');assert.equal(d.querySelector('#org-name').textContent,'Product Manager');assert.equal(d.querySelector('#org-state').textContent,'Expansion role');assert(d.querySelector('#org-image').getAttribute('src').startsWith(basePath+'/assets/'));click('[data-department="Engineering"]');assert.equal(d.querySelector('#org-name').textContent,'QA Engineer');
click('[data-workflow="3"]');assert.equal(d.querySelector('#workflow-state').textContent,'Approval required');click('#workflow-next');assert.equal(d.querySelector('#workflow-title').textContent,'Record the decision');click('[data-policy="3"]');assert.equal(d.querySelector('#policy-outcome').textContent,'REQUIRE APPROVAL');click('[data-policy="6"]');assert.equal(d.querySelector('#policy-outcome').textContent,'DENY');
click('.menu-toggle');assert.equal(d.querySelector('.menu-toggle').getAttribute('aria-expanded'),'true');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(d.querySelector('.menu-toggle').getAttribute('aria-expanded'),'false');click('.theme-toggle');assert.equal(w.localStorage.getItem('af-theme'),'dark');click('.motion-toggle');assert.equal(w.localStorage.getItem('af-motion'),'paused');assert.equal(d.querySelector('video').dataset.wasPaused,'true');assert(d.querySelector('video').controls);assert(!d.querySelector('video').autoplay);assert.equal(d.querySelector('video').preload,'none');assert(d.querySelector('track[kind=captions][srclang=en]'));
d.querySelector('textarea').value='Pilot question <script>test</script>';d.querySelector('form').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(d.querySelector('#inquiry-draft').hidden,false);assert.match(d.querySelector('#inquiry-status').textContent,/Not sent/);assert(!d.querySelector('#draft-text script'));assert(!d.querySelector('#contact').textContent.includes('akki77parekh@gmail.com'));home.window.close();
const product=boot('/product/');product.window.document.querySelector('[data-capability="7"]').click();assert.equal(product.window.document.querySelector('#capability-status').textContent,'Implemented');product.window.close();
const cat=boot('/ai-employees/'),c=cat.window.document;const visible=()=>[...c.querySelectorAll('.workforce-card')].filter(e=>!e.hidden);assert.equal(visible().length,9);c.querySelector('#show-all').click();assert.equal(visible().length,55);[...c.querySelectorAll('[data-department-filter]')].find(e=>e.dataset.departmentFilter==='People & HR').click();assert.equal(visible().length,3);c.querySelector('#clear-filters').click();const search=c.querySelector('#agent-search');search.value='reconciliation';search.dispatchEvent(new cat.window.Event('input'));assert.equal(visible().length,1);assert.equal(visible()[0].dataset.name,'Accounto');visible()[0].querySelector('.role-details').click();assert.equal(c.querySelector('#role-dialog').open,true);assert.equal(c.querySelector('#role-title').textContent,'Accountant');c.querySelector('#close-role').click();assert.equal(c.querySelector('#role-dialog').open,false);search.value='no-such-role';search.dispatchEvent(new cat.window.Event('input'));assert.equal(c.querySelector('#catalog-empty').hidden,false);cat.window.close();
// Commercial pages must distinguish current MIT availability from proposed services.
assert.equal(docs.get('/pricing/').querySelectorAll('.price-card').length,4);
assert.match(docs.get('/pricing/').body.textContent,/indicative early-access plans/);
assert(!docs.get('/pricing/').querySelector('form[action]'));
const guides=boot('/docs/'),gd=guides.window.document;
gd.querySelector('[data-doc-filter="managed"]').click();
assert(gd.querySelector('#community-docs').hidden);assert(!gd.querySelector('#managed-docs').hidden);
gd.querySelector('[data-doc-filter="all"]').click();assert(!gd.querySelector('#community-docs').hidden);
guides.window.close();
const inquiry=boot('/contact/'),iq=inquiry.window.document;
iq.querySelector('[name="company"]').value='Example organization';iq.querySelector('textarea').value='Discuss Team access';
iq.querySelector('form').dispatchEvent(new inquiry.window.Event('submit',{cancelable:true}));
assert.match(iq.querySelector('#draft-text').textContent,/Organization: Example organization/);
assert.match(iq.querySelector('#inquiry-status').textContent,/Not sent/);inquiry.window.close();
console.log(`PASS: ${docs.size} routes, ${links} local links/assets, metadata, unique IDs, source-aligned policy, org/capability/workflow controls, catalog/filter/dialog, theme/motion/menu, bounded 3D pointer effects, edition boundaries, docs filtering and safe inquiry drafts.`);
