import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {pages} from './public-pages.mjs';
import {repo,origin,roles,capabilities,workflow,policy,docs,wiki,baseline} from './public-data.mjs';
import {esc} from './public-components.mjs';
import {basePath,prefixLinks} from './site-config.mjs';
const out=fileURLToPath(new URL('./dist/',import.meta.url));
fs.mkdirSync(out,{recursive:true});
fs.cpSync(fileURLToPath(new URL('./public/',import.meta.url)),out,{recursive:true});
const css=path.join(out,'public.css');
fs.writeFileSync(css,fs.readFileSync(css,'utf8').replaceAll("url('/assets/",`url('${basePath}/assets/`));
// A changed stylesheet gets a new URL, even when the browser has cached the old one.
const styleVersions=Object.fromEntries(['public.css','modern.css','depth.css','commerce.css'].map(name=>[name,createHash('sha256').update(fs.readFileSync(path.join(out,name))).digest('hex').slice(0,12)]));
const versionStyles=html=>html.replace(/href="\/(public\.css|modern\.css|depth\.css|commerce\.css)"/g,(_,name)=>`href="/${name}?v=${styleVersions[name]}"`);
fs.writeFileSync(path.join(out,'.nojekyll'),'');
const navItems=[['Product','/product/'],['AI employees','/ai-employees/'],['Pricing','/pricing/'],['Community','/community/'],['Docs','/docs/'],['Developers','/developers/'],['Contact us','/contact/']];
const brand='<a class="brand" href="/" aria-label="Agents Foundry home"><span class="brand-mark" aria-hidden="true">AF</span><span>Agents Foundry</span></a>';
const footer=`<footer class="container site-footer"><div>${brand}<p>Build your AI workforce.<br>Run it like a real organization.</p></div><nav aria-label="Product footer"><strong>Platform</strong>${[['Product','/product/'],['AI employees','/ai-employees/'],['Architecture','/architecture/'],['Security','/security/'],['Use cases','/use-cases/']].map(([t,u])=>`<a href="${u}">${t}</a>`).join('')}</nav><nav aria-label="Resources footer"><strong>Resources</strong><a href="/developers/">Developers</a><a href="/community/">Community</a><a href="/docs/">Docs hub</a><a href="${wiki}">Technical wiki</a><a href="/contributing.html">Contribute</a><a href="${repo}">GitHub</a><a href="${docs}">Documentation</a></nav><nav aria-label="Company footer"><strong>Company</strong><a href="/company/">About</a><a href="/investors/">Investors</a><a href="/pricing/">Pricing & editions</a><a href="/contact/">Contact us</a><a href="/privacy/">Website privacy</a><a href="/login/">Workspace access</a></nav><p class="footer-note">Agents Foundry · Organizational infrastructure for AI work. Product availability is described alongside each capability. <a href="${repo}/commit/${baseline}">Source baseline · ${baseline.slice(0,7)}</a>.</p></footer>`;
for(const [route,page] of Object.entries(pages)){
 const canonical=origin+route;const title=page.title+' | Agents Foundry';
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(page.description)}"><link rel="canonical" href="${canonical}"><meta name="robots" content="${page.noindex?'noindex,follow':'index,follow'}"><meta property="og:type" content="website"><meta property="og:site_name" content="Agents Foundry"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${canonical}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(page.description)}"><meta name="color-scheme" content="light dark"><link rel="icon" href="/assets/brand.svg" type="image/svg+xml"><link rel="preload" href="/assets/dm-sans.woff2" as="font" type="font/woff2" crossorigin><script src="/preferences.js"></script><link rel="stylesheet" href="/public.css"><link rel="stylesheet" href="/modern.css"><link rel="stylesheet" href="/depth.css"><link rel="stylesheet" href="/commerce.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'Agents Foundry',url:origin,description:page.description})}</script></head><body><a class="skip-link" href="#main-content">Skip to main content</a><header class="site-header"><div class="nav-shell">${brand}<div class="nav-controls"><button class="icon-button theme-toggle" aria-label="Switch theme">Theme</button><button class="icon-button motion-toggle" aria-pressed="false">Pause motion</button><button class="icon-button menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button></div><nav id="main-nav" aria-label="Main navigation">${navItems.map(([t,u])=>`<a href="${u}" ${u===route?'aria-current="page"':''}>${t}</a>`).join('')}<a href="/login/">Sign in</a></nav></div></header><main id="main-content" tabindex="-1">${page.body}</main>${footer}<script id="public-data" type="application/json">${JSON.stringify({roles,capabilities,workflow,policy}).replaceAll('<','\\u003c')}</script><script src="/public.js" defer></script><script src="/depth.js" defer></script></body></html>`;
 const file=route.endsWith('.html')?path.join(out,route):path.join(out,route,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,prefixLinks(versionStyles(html.replace('"roles":',`"basePath":${JSON.stringify(basePath)},"roles":`))));
}
fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: ${basePath}/api/\nDisallow: ${basePath}/admin/\nDisallow: ${basePath}/employee/\nDisallow: ${basePath}/login/\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.entries(pages).filter(([,p])=>!p.noindex).map(([route])=>`<url><loc>${origin}${route}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(path.join(out,'404.html'),prefixLinks(versionStyles(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | Agents Foundry</title><meta name="robots" content="noindex"><link rel="stylesheet" href="/public.css"></head><body><main class="page-intro container"><h1>This page isn’t here.</h1><p>Return to the platform or explore the implementation.</p><a class="button primary" href="/">Agents Foundry home</a></main></body></html>`)));
console.log(`Built ${Object.keys(pages).length} crawlable public pages, sitemap and robots.txt.`);
