import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {JSDOM,VirtualConsole} from 'jsdom';import {pages} from './public-pages.mjs';import {policy} from './public-data.mjs';
const base=fileURLToPath(new URL('./dist/',import.meta.url));
import {origin,basePath} from './site-config.mjs';
const fileFor=p=>path.join(base,p.endsWith('.html')?p:p+'/index.html');
const docs=new Map(Object.keys(pages).map(route=>[route,new JSDOM(fs.readFileSync(fileFor(route),'utf8')).window.document]));let links=0;
for(const [route,d] of docs){assert.equal(d.querySelectorAll('h1').length,1,route+' h1');assert(d.querySelector('main#main-content'));assert(d.querySelector('meta[name=description]').content.length>40);assert.equal(d.querySelector('link[rel=canonical]').href,origin+route);assert(d.querySelector('meta[property="og:title"]'));assert(d.querySelector('meta[name="twitter:card"]'));const ids=[...d.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size,'Duplicate ID '+route);
 for(const el of d.querySelectorAll('[href],[src]')){const ref=el.getAttribute('href')||el.getAttribute('src');if(!ref||/^(https?:|mailto:|data:)/.test(ref))continue;const url=new URL(ref,origin+route);assert(url.pathname.startsWith(basePath+'/'),`${route}: unprefixed path ${ref}`);const localPath=url.pathname.slice(basePath.length)||'/',target=docs.get(localPath);if(target){if(url.hash)assert(target.getElementById(url.hash.slice(1)),`${route}: broken anchor ${ref}`);}else assert(fs.existsSync(path.join(base,localPath)),`${route}: missing asset ${ref}`);links++;}
}
assert(docs.get('/login/').querySelector('meta[name=robots]').content.includes('noindex'));assert(!docs.get('/login/').querySelector('input[type=password]'));assert(!fs.readFileSync(path.join(base,'sitemap.xml'),'utf8').includes('/login/'));
// Public policy explanations must match the actual engine, not an aspirational workflow.
const contract=JSON.parse(fs.readFileSync(new URL('./tests/policy-contract.json',import.meta.url),'utf8'));for(const [action,,outcome] of policy.slice(0,-1)){assert.equal(outcome,contract.actions[action],'Policy mismatch '+action);}
function boot(route){const dom=new JSDOM(fs.readFileSync(fileFor(route),'utf8'),{url:origin+route,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole().on('jsdomError',error=>{throw error;})}),w=dom.window;w.matchMedia=()=>({matches:false,addEventListener(){}});w.ResizeObserver=class{observe(){}};w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};for(const s of ['preferences.js','public.js'])w.eval(fs.readFileSync(path.join(base,s),'utf8'));return dom;}
for(const route of Object.keys(pages)){const dom=boot(route);dom.window.close();}
const home=boot('/'),w=home.window,d=w.document;const click=s=>{assert(d.querySelector(s),s);d.querySelector(s).click();};
click('[data-department="Product"]');assert.equal(d.querySelector('#org-name').textContent,'Product Manager');assert.equal(d.querySelector('#org-state').textContent,'Planned role');assert(d.querySelector('#org-image').getAttribute('src').startsWith(basePath+'/assets/'));click('[data-department="Engineering"]');assert.equal(d.querySelector('#org-name').textContent,'QA Engineer');
click('[data-workflow="3"]');assert.equal(d.querySelector('#workflow-state').textContent,'Approval required');click('#workflow-next');assert.equal(d.querySelector('#workflow-title').textContent,'Record the decision');click('[data-policy="3"]');assert.equal(d.querySelector('#policy-outcome').textContent,'REQUIRE APPROVAL');click('[data-policy="6"]');assert.equal(d.querySelector('#policy-outcome').textContent,'DENY');
click('.menu-toggle');assert.equal(d.querySelector('.menu-toggle').getAttribute('aria-expanded'),'true');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(d.querySelector('.menu-toggle').getAttribute('aria-expanded'),'false');click('.theme-toggle');assert.equal(w.localStorage.getItem('af-theme'),'dark');click('.motion-toggle');assert.equal(w.localStorage.getItem('af-motion'),'paused');
d.querySelector('textarea').value='Pilot question <script>test</script>';d.querySelector('form').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(d.querySelector('#inquiry-draft').hidden,false);assert.match(d.querySelector('#inquiry-status').textContent,/Not sent/);assert(!d.querySelector('#draft-text script'));assert(!d.querySelector('#contact').textContent.includes('akki77parekh@gmail.com'));home.window.close();
const product=boot('/product/');product.window.document.querySelector('[data-capability="7"]').click();assert.equal(product.window.document.querySelector('#capability-status').textContent,'Planned');product.window.close();
const cat=boot('/ai-employees/'),c=cat.window.document;const visible=()=>[...c.querySelectorAll('.workforce-card')].filter(e=>!e.hidden);assert.equal(visible().length,9);c.querySelector('#show-all').click();assert.equal(visible().length,55);[...c.querySelectorAll('[data-department-filter]')].find(e=>e.dataset.departmentFilter==='People & HR').click();assert.equal(visible().length,3);c.querySelector('#clear-filters').click();const search=c.querySelector('#agent-search');search.value='reconciliation';search.dispatchEvent(new cat.window.Event('input'));assert.equal(visible().length,1);assert.equal(visible()[0].dataset.name,'Accounto');visible()[0].querySelector('.role-details').click();assert.equal(c.querySelector('#role-dialog').open,true);assert.equal(c.querySelector('#role-title').textContent,'Accountant');c.querySelector('#close-role').click();assert.equal(c.querySelector('#role-dialog').open,false);search.value='no-such-role';search.dispatchEvent(new cat.window.Event('input'));assert.equal(c.querySelector('#catalog-empty').hidden,false);cat.window.close();
console.log(`PASS: ${docs.size} routes, ${links} local links/assets, metadata, unique IDs, source-aligned policy, org/capability/workflow controls, catalog/filter/dialog, theme/motion/menu and safe inquiry drafts.`);
